//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsCatalog.Client {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ProductsCatalog.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string ReturnBack {
            get {
                return ResourceManager.GetString("ReturnBack", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteCatalog {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteCatalog", resourceCulture);
            }
        }
        
        internal static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string NoOneCategoriesWereFound {
            get {
                return ResourceManager.GetString("NoOneCategoriesWereFound", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Add_aNewCategory {
            get {
                return ResourceManager.GetString("Add_aNewCategory", resourceCulture);
            }
        }
        
        internal static string Catalogs {
            get {
                return ResourceManager.GetString("Catalogs", resourceCulture);
            }
        }
        
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string NavigateToCatalogList {
            get {
                return ResourceManager.GetString("NavigateToCatalogList", resourceCulture);
            }
        }
        
        internal static string NavigateToCategoriesList {
            get {
                return ResourceManager.GetString("NavigateToCategoriesList", resourceCulture);
            }
        }
        
        internal static string CatalogTitle {
            get {
                return ResourceManager.GetString("CatalogTitle", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string LockoutUser {
            get {
                return ResourceManager.GetString("LockoutUser", resourceCulture);
            }
        }
        
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        internal static string AddaNewUser {
            get {
                return ResourceManager.GetString("AddaNewUser", resourceCulture);
            }
        }
        
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        internal static string Lockouted {
            get {
                return ResourceManager.GetString("Lockouted", resourceCulture);
            }
        }
        
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        internal static string AddaProduct {
            get {
                return ResourceManager.GetString("AddaProduct", resourceCulture);
            }
        }
        
        internal static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteProduct {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteProduct", resourceCulture);
            }
        }
        
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        internal static string AreYouSureToDeleteProductCategory {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteProductCategory", resourceCulture);
            }
        }
        
        internal static string AddaNewProduct {
            get {
                return ResourceManager.GetString("AddaNewProduct", resourceCulture);
            }
        }
        
        internal static string NoOneProductWasFound {
            get {
                return ResourceManager.GetString("NoOneProductWasFound", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SearchCategoryByName {
            get {
                return ResourceManager.GetString("SearchCategoryByName", resourceCulture);
            }
        }
        
        internal static string NavigateToProductsList {
            get {
                return ResourceManager.GetString("NavigateToProductsList", resourceCulture);
            }
        }
    }
}
